#!/bin/python3

import math
import os
import random
import re
import sys

#
# Complete the 'pickingNumbers' function below.
#
# The function is expected to return an INTEGER.
# The function accepts INTEGER_ARRAY a as parameter.
#

def pickingNumbers(a):
    # Write your code here
    lis1 = [0 for i in range(max(a)+1)]
    for i in range(len(a)):
        lis1[a[i]] = lis1[a[i]] + 1
    max1 = 0
    for i in range(len(lis1)-1):
        r = lis1[i] + lis1[i+1]
        if r > max1:
            max1 = r
    return max1



if __name__ == '__main__':
    fptr = open(os.environ['OUTPUT_PATH'], 'w')

    n = int(input().strip())

    a = list(map(int, input().rstrip().split()))

    result = pickingNumbers(a)

    fptr.write(str(result) + '\n')

    fptr.close()
